apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management
        image: iMrSeba/Users-MS:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: user-management
spec:
  type: NodePort
  selector:
    app: user-management
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
